Legacy ERB template support
DavidS/puppetlabs-ntp pull request #7
Opened 2016-09-27 14:11 UTC by wilson208

Introduced config_epp and step_tickers_epp parameters which accept EPP templates and reverted the config_template and step_tickers_template back to support ERB templates

2016-09-27 14:50 UTC, DavidS requested changes
A great start!

I've left a few comments around testing, and the docs. Please address them.

If you have additional cycles, changing the test templates to actually use the ERB/EPP syntax (to prove that the correct evaluator is used) would be terrific.

2016-09-27 14:50 UTC, DavidS commented on README.markdown
> +  config_epp => 'different/module/custom.template.epp',
Rockets (=>) should always align, for easier reading.

2016-09-27 14:50 UTC, DavidS commented on README.markdown
> +Specifies a file to act as a ERB template for the config file. Valid options: string containing a path (absolute, or relative to the module path). Default value: 'ntp/ntp.conf.erb'. Validation error
The default here is not right. Maybe say "example value", so that people have something to grab onto.

2016-09-27 14:50 UTC, DavidS commented on README.markdown
> +Location of the step tickers ERB template file. Default value: varies by operating system. Validation error will be thrown if this is specified as well as the `step_tickers_epp` param.
Same here about the default value.

2016-09-27 14:50 UTC, DavidS commented on README.markdown
> +Location of the step tickers EPP template file. Default value: varies by operating system. Validation error will be thrown if this is specified as well as the `step_tickers_template` param.
Does it actually differ by OS? Your change below doesn't support that.

2016-09-27 14:50 UTC, DavidS commented on spec/acceptance/ntp_parameters_spec.rb
> +      its(:content) { should match 'testcontent' }
This test needs to prove that the correct template is used. Put different content into the test templates to do so.

2016-09-27 14:50 UTC, DavidS commented on spec/classes/ntp_spec.rb
> +          it { should contain_file('/etc/ntp.conf').with({ 'content' => /server foobar/}) }
Like the acceptance test, this should prove that the right template is used.

2016-09-27 15:06 UTC, wilson208 commented on README.markdown
> +Location of the step tickers EPP template file. Default value: varies by operating system. Validation error will be thrown if this is specified as well as the `step_tickers_template` param.
This varies by OS in that in Redhat.yaml a step_tickers_file value is supplied whereas in every other OS it is not. So on redhat the default behaviour is to use the default step-tickers.epp template file whereas on other OS's by default no step-tickers file is used.

2016-09-27 19:20 UTC, DavidS commented on README.markdown
> +Location of the step tickers EPP template file. Default value: varies by operating system. Validation error will be thrown if this is specified as well as the `step_tickers_template` param.
urgh.

2016-09-28 11:07 UTC, DavidS approved these changes

2016-09-28 11:07 UTC, merged